### ISSUE TITLE
Where the data comes from?

### ISSUE THREAD

**Issue by Gomesmig** [MummyDing/Awesome-Campus#31]
Where the data comes from?
Sorry for the noob question
and thanks

**Comment by KevinWu1993** [comment]
@Gomesmig Part of data comes from websites response.
Just like to send a get request via Postman and then parse the response by Jsoup.

More about Jsoup(https://jsoup.org/)

**Comment by MummyDing** [comment]
@Gomesmig 
Actually, the data source can be divided into two parts:
1. Public API. It is well designed because it response to JSON format data.There are lots of public APIs, such as [Science API](https://github.com/MummyDing/Awesome-Campus/blob/dev/app/src/main/java/cn/edu/jxnu/awesome_campus/api/ScienceApi.java)
2. The plain HTML Page Data. We fetch it and parse it by [jsoup](https://jsoup.org/) .Kevin has already mentioned it.
